tcp:
  routers:
    grpc-router:
      entryPoints:
        - grpc
      rule: "HostSNI(`*`)"
      service: grpc-service
      tls: false
  services:
    grpc-service:
      loadBalancer:
        servers:
          - address: "go-app:50051"